name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Install Chromium
      run: sudo apt-get install -y chromium-browser

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Run login tests
      run: npm run test:login

    - name: Run sign-up tests
      run: npm run test:sign_up

    - name: Run contact-us tests
      run: npm run test:contact_us

    - name: Run shop tests
      run: npm run test:shop

    - name: Run trust-center tests
      run: npm run test:trust_center

    - name: Run main tests
      run: npm run test:main

    - name: Generate Allure report
      run: npm run allure:generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token:  ${{ secrets.GH_TOKEN }}
        publish_dir: ./allure-report
