name: In Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t wdio-tests .

      - name: Run Login Test
        run: docker run --rm wdio-tests npm run test:login

      - name: Run Sign Up Test
        run: docker run --rm wdio-tests npm run test:sign_up

      - name: Run Contact Us Test
        run: docker run --rm wdio-tests npm run test:contact_us

      - name: Run Trust Center Test
        run: docker run --rm wdio-tests npm run test:trust_center

      - name: Run Subscription Test
        run: docker run --rm wdio-tests npm run test:subscription

      - name: Run Support_center Test
        run: docker run --rm wdio-tests npm run test:support_center

      - name: Run Marketplace Test
        run: docker run --rm wdio-tests npm run test:marketplace

      - name: Run Developers Test
        run: docker run --rm wdio-tests npm run test:developers

      - name: Run Social Media Test
        run: docker run --rm wdio-tests npm run test:social_media

      - name: Run Login Test (Firefox)
        run: docker run --rm wdio-tests npm run test:login-firefox

      - name: Run Shop Test
        run: docker run --rm wdio-tests npm run test:shop
